### ISSUE TITLE
alterator provision template has fixed password

### ISSUE THREAD

**Issue by domcleal** [theforeman/community-templates#113]
The alterator provision template should use the root password hash provided in Foreman and not have "123" hardcoded as a root password, if possible.

**Comment by tbrisker** [comment]
On behalf of the Foreman team, thank you for your contribution to the Foreman community templates repository! 
This repository is being archived and all templates are migrated to the relevant repositories. If you wish to pursue this issue, please re-open the issue against the relevant project in our [issue tracker](https://projects.theforeman.org). 
For more information and background, please [click here]( https://community.theforeman.org/t/heads-up-community-templates-repo-will-be-archived-tomorrow/19539).
