### ISSUE TITLE
Ubuntu 14.04 reports "cannot find a GRUB device for default"

### ISSUE THREAD

**Issue by domcleal** [theforeman/community-templates#154]
@sathieu reports on 4097b83 that 14.04 throws an error during installation: `grub-installer: cannot find a GRUB drive for default`

**Comment by mmoll** [comment]
@sathieu I can't reproduce in my KVM test-setup. Could you make extra sure, backing out that change fixes the problem for you and/or if setting the ```install-disk``` host parameter fixes it?

**Comment by mmoll** [comment]
Sorry, error on my end. ```install-disk``` works, PR incoming soon.

**Comment by mmoll** [comment]
closed by merging #155
