### ISSUE TITLE
Empty space in 'userdata' scripts breaks cloud-init

### ISSUE THREAD

**Issue by justicel** [theforeman/community-templates#165]
If there is an empty space at the top of any user-data script, cloud-init gets mad and quits. It is looking for the #! as the very first line. This code adds an empty line:

<%#
kind: user_data
name: Preseed default user data
oses:
- Debian 6.0
- Debian 7.
- Debian 8.
- Ubuntu 12.04
- Ubuntu 14.04
%>

**Comment by mmoll** [comment]
Could you open a PR for that?

**Comment by derektamsen** [comment]
I have the same issue submitting a PR to fix it.
