### ISSUE TITLE
Preseed networking setup

### ISSUE THREAD

**Issue by domcleal** [theforeman/community-templates#173]
A networking setup snippet is required for preseed OSes that can configure interfaces either inside the main preseed configuration, or be called from a finish script.

Here's the kickstart version for reference: https://github.com/theforeman/community-templates/blob/master/snippets/kickstart_networking_setup.erb

Alternatively, we could combine them into something more cross-platform such as netcf (http://projects.theforeman.org/issues/7460).

**Comment by ares** [comment]
I put something together that seemed to work (in ~1.7). There was the issue with debian installer that removed customized interfaces file just before reboot, so we didn't merge it. If there's someone who'd like to work on this, here's [the gist](https://gist.github.com/ares/9fc36e66039274cb165a). Also here's the potential workaround for the reboot issue http://projects.theforeman.org/projects/foreman/wiki/Tips_&amp_Tricks#Debian-based-Tips

**Comment by mmoll** [comment]
PR: #234
