### ISSUE TITLE
Error while define PXE default

### ISSUE THREAD

**Issue by sjkeerthi** [theforeman/community-templates#186]
Hi All 

I tried to build my own template for the CentOS 6 / 7 with my customization.

I found error while I build the host.

Templates

Failure parsing Kickstart-CTF default: undefined local variable or method `proxy_string' for #Host::Managed:0x0000000988aff0. 

My Template.

<pre>
<%#
kind: provision
name: Kickstart-CTF default
oses:
- CentOS 6
- CentOS 7
%>
<%#
This template accepts the following parameters:
- lang: string (default="en_US.UTF-8")
- keyboard: string (default="us")
- time-zone: string (default="UTC")
- http-proxy: string (default="")
- http-proxy-port: string (default="")
- force-puppet: boolean (default=false)
- enable-puppetlabs-repo: boolean (default=false)
- salt_master: string (default=undef)
- ntp-server: string (default="ntp1.sjc.collab.net")
%>
install
<%= @mediapath %><%= proxy_string %>
lang <%= @host.params['lang'] || 'en_US.UTF-8' %>
selinux --permissive
keyboard <%= @host.params['keyboard'] || 'us' %>
skipx

<% subnet = @host.subnet -%>
<% if subnet.respond_to?(:dhcp_boot_mode?) -%>
<% dhcp = subnet.dhcp_boot_mode? && !@static -%>
<% else -%>
<% dhcp = !@static -%>
<% end -%>

network --bootproto <%= dhcp ? 'dhcp' : "static --ip=#{@host.ip} --netmask=#{subnet.mask} --gateway=#{subnet.gateway} --nameserver=#{[subnet.dns_primary, subnet.dns_secondary].select(&:present?).join(',')}" %> --device=<%= @host.mac -%> --hostname <%= @host %>
rootpw --iscrypted <%= root_pass %>
firewall --disabled
authconfig --useshadow --passalgo=sha256 --kickstart
timezone --utc <%= @host.params['time-zone'] || 'UTC' %>

<% if @dynamic -%>
%include /tmp/diskpart.cfg
<% else -%>
<%= @host.diskLayout %>
<% end -%>

text
reboot

%packages
yum
dhclient
ntp
wget
@Core
@system-admin-tools
acl
at
attr
audit
authconfig
bb_client
bc
bind-libs
bind-utils
blktrace
bzip2
cnops-janitor
collabnet_monitor
compat-libstdc++-296
compat-libstdc++-33
cronie
crontabs
crypto-utils
cvs
dos2unix
dropwatch
dstat
dtach
elinks
emacs-nox
expect
file
fipscheck
gdb
git
gnutls-utils
hardlink
hp-health
hp-scripting-tools
hp-snmp-agents
hpacucli
hponcfg
httpd-tools
iotop
iproute
iptraf
iputils
jwhois
kernel
ksh
lftp
libxml2
libxslt
lm_sensors
logrotate
lslk
lsof
lsscsi
ltrace
m2crypto
mailcap
make
man
man-pages
man-pages-overrides
mcelog
mcollective
mcollective-common
mgetty
microcode_ctl
mlocate
nc
net-snmp
net-snmp-utils
nfs-utils
nmap
nss-tools
ntp
numactl
openssh
openssh-clients
openssh-server
openssl
openssl098e
patch
patchutils
pax
pciutils
perf
perl
pinfo
powertop
psacct
psmisc
puppet
rng-tools
rsync
rsyslog
ruby
ruby-irb
screen
sendmail
setools-console
strace
sudo
symlinks
sysfsutils
sysstat
tcl
tcp_wrappers
tcpdump
telnet
time
traceroute
tree
tuned
tuned-utils
units
unix2dos
unzip
vim-enhanced
wget
which
words
x86info
xinetd
yum
yum-plugin-changelog
yum-plugin-downloadonly
yum-plugin-tmprepo
yum-plugin-verify
yum-plugin-versionlock
yum-utils
zip
zsh

<%= section_end -%>

<% if @dynamic -%>
%pre
<%= @host.diskLayout %>
<%= section_end -%>
<% end -%>

%post --nochroot
exec < /dev/tty3 > /dev/tty3
#changing to VT 3 so that we can see whats going on....

/usr/bin/chvt 3
(
cp -va /etc/resolv.conf /mnt/sysimage/etc/resolv.conf
/usr/bin/chvt 1
) 2>&1 | tee /mnt/sysimage/root/install.postnochroot.log
<%= section_end -%>

%post
logger "Starting anaconda <%= @host %> postinstall"
exec < /dev/tty3 > /dev/tty3
#changing to VT 3 so that we can see whats going on....
/usr/bin/chvt 3
(
<% if subnet.respond_to?(:dhcp_boot_mode?) -%>
<%= snippet 'kickstart_networking_setup' %>
<% end -%>

#update local time
echo "updating system time"
/usr/sbin/ntpdate -sub <%= @host.params['ntp-server'] || 'ntp1.sjc.collab.net' %>
/usr/sbin/hwclock --systohc

# update all the base packages from the updates repository
#yum -t -y -e 0 update

# Setup puppet to run on system reboot
/sbin/chkconfig --level 345 puppet on

sync

# Inform the build system that we are done.
echo "Informing Foreman that we are built"
wget -q -O /dev/null --no-check-certificate <%= kicker.sjc.collab.net %>
) 2>&1 | tee /root/install.post.log
exit 0
#<%= section_end -%>
</pre>

**Comment by domcleal** [comment]
This appears to be our template, but you have removed the important line here that sets proxy_string:

https://github.com/theforeman/community-templates/blob/master/kickstart/provision.erb#L34

Yet on one of the first few lines, there's still a reference to it:

```
<%= @mediapath %><%= proxy_string %>
```

Remove that part, or put back the line that defines the variable.

Since this isn't a bug with the original template, I'd suggest bringing questions about how to modify templates to the foreman-users mailing list or IRC: http://theforeman.org/support.html
