### ISSUE TITLE
Make the Template as my ks.cfg Why so complicated.

### ISSUE THREAD

**Issue by sjkeerthi** [theforeman/community-templates#187]
Hi All,

The defining the kickstart template is too complicated like programmatic way. 

Compare to Normal Kickstart defining ks.cfg more easy than foreman. 

There should be a options to upload the ks.cfg which should either convertible into template or else kc.cfg should work.

**Comment by domcleal** [comment]
You can create your own templates in Foreman under Hosts > Provisioning Templates.  It can be as simple or complicated as you like - you can upload a file, or write it from scratch.  The default is meant to cover a large number of operating systems and scenarios, you don't have to use it.
