### ISSUE TITLE
ubuntu 12.04 - static keyword is not working

### ISSUE THREAD

**Issue by dgagnon** [theforeman/community-templates#213]
even though the rendered template shows a static network configuration, /etc/network/interface is configured as dhcp after reboot.

**Comment by mmoll** [comment]
this is a known problem of the installer: https://github.com/theforeman/community-templates/pull/208#issuecomment-146773347

**Comment by dgagnon** [comment]
I am aware of the issue about changing the /etc/network/interface during the installer.  On debian 7 and 8 and ubuntu 14, configuring static networking using the preseed file works great.

This is for a single interface install, nothing fancy.

**Comment by mmoll** [comment]
OK, so this is Ubuntu/precise specific. If this can get fixed in the generated preseed syntax: PRs welcome, otherwise this is an installer bug. Diagnosing this further would require quite some time of doc reading, bug searching and testing...

**Comment by dgagnon** [comment]
Correct. 

From https://help.ubuntu.com/12.04/installation-guide/example-preseed.txt, I added the following and it fixed the problem on ubuntu 12.  Running my tests to see if it breaks other installs.

```
<% unless dhcp -%>
# Static network configuration.
d-i preseed/early_command string /bin/killall.sh; /bin/netcfg
d-i netcfg/disable_autoconfig boolean true
d-i netcfg/dhcp_failed note
d-i netcfg/dhcp_options select Configure network manually
```

**Comment by dgagnon** [comment]
fix confirmed working on debian7, debian8, ubuntu12 and ubuntu14.  Only tested static networking.  
If someone wants to confirm it works on what I cant test, I will submit a PR.

**Comment by mmoll** [comment]
Just submit a PR, I'll test with DHCP then :+1:

**Comment by dgagnon** [comment]
PR #219 all yours

**Comment by dgagnon** [comment]
My template rendering was erroring on:

+<% if (param_true? @host.params['enable-puppetlabs-repo']) -%>

Reverting these line allowed my template to render without error.  I changed the rest of the param_true? that were used as boolean test without using the output of the method to allow unit testing to pass.

**Comment by mmoll** [comment]
you are right, see #220 :bow:
