### ISSUE TITLE
tests failing: undefined method `param_true?' for RHEL:FakeStruct

### ISSUE THREAD

**Issue by mmoll** [theforeman/community-templates#215]
since the merge of #212

**Comment by dgagnon** [comment]
confirmed, broke all my centos installs.

**Comment by dgagnon** [comment]
If you merge my latest PR, I applied a fix:

-<% if (param_true? @host.params['enable-puppetlabs-repo']) -%>
+<% if @host.params['enable-puppetlabs-repo'] -%>

**Comment by dgagnon** [comment]
it also fixes the CI failure from my PR

**Comment by dgagnon** [comment]
Fix in:

Fixes param_true? issue and ubuntu 12 static networking #219

**Comment by mmoll** [comment]
@dgagnon the commited code works fine for me (with Foreman 1.10), it's a test failure, as the param_true method must get added to the faked data structure. What problems did you see?

**Comment by mmoll** [comment]
@dgagnon see #220

**Comment by dgagnon** [comment]
thanks for the excellent work. @mmoll

**Comment by mmoll** [comment]
the tests will still fail because of the missing method in FakeStruct
