### ISSUE TITLE
UserData default is lacking in features

### ISSUE THREAD

**Issue by edestecd** [theforeman/community-templates#279]
The default cloud init template does not do the following that all the other templates seem to do:
- Install an automation tool (puppet/chef/salt)
- Patch the system (yum or apt)
- reboot

In addition, it creates an admin account with a password, which is against standard best practices in cloud providers.
Read the section under passwd: http://cloudinit.readthedocs.io/en/latest/topics/examples.html#including-users-and-groups
Remember user data can be seen by anyone, for example EC2 stores this with the instance for later editing/reference.

Is this intentional?
Would you take a PR that attempts to solve all of these?
I have been working up a template in our environment that seems to work on CentOS/Fedora/Debain/Ubuntu.

**Comment by ekohl** [comment]
I think we're certainly open to PRs to solve it.

**Comment by domcleal** [comment]
Indeed, though I'd add emphasis perhaps on PR**s** - it's a lot of things to fix in one go. We have some snippets that could be incorporated for things like config management setup, so I think we'd want to maximise reuse and code-sharing.

The finish templates have got out of sync with network provisioning templates in the past, so I'd hate for this to happen again with user_data.

There's an `indent` helper that might be useful for constructing YAML containing scripts from snippets.

**Comment by edestecd** [comment]
My solution uses the new snippets for puppet/chef/salt.
I also ran into the indent issue and used gsub to solve it.  The `indent` helper would be nice.  I'll try it.

I will make multiple PRs.  One for each feature.

**Comment by edestecd** [comment]
Where is the indent helper documented? Can I get an example?

**Comment by domcleal** [comment]
http://projects.theforeman.org/projects/foreman/wiki/TemplateWriting#Functions-and-macros

**Comment by edestecd** [comment]
I have created 3 separate issues in Redmine:
http://projects.theforeman.org/issues/15359
http://projects.theforeman.org/issues/15358
http://projects.theforeman.org/issues/15360
