### ISSUE TITLE
Community template for OpenSuSE Leap 42 AutoYast?

### ISSUE THREAD

**Issue by lawre** [theforeman/community-templates#284]
Has anyone tried OpenSuSE Leap 42 with our existing AutoYast templates?  Does it work ok?  If not, what are some of the gotchas?  I plan on making an initial deployment this week and hope to get a heads up on any issues I may run into.  Thanks!

**Comment by mmoll** [comment]
It did work last time I tried, only Puppet was broken in OpenSuSE itself.

**Comment by lawre** [comment]
Thanks for the quick reply Mike!

**Comment by lawre** [comment]
Mike, can you elaborate on puppet being broken in OpenSuSE?  I myself have run into an issue with every time puppet runs, it wants to pop up Yast2 during the facter -p run.  My google-fu is not working to find others with this issue.

**Comment by mmoll** [comment]
Sorry, I didn't look further back then, as, fortunately, I don't have to care about SuSE at the moment. :snake: 

IIRC the install of the package itself was already broken because some dependency was just not in Leap anymore, so a different issue...
