### ISSUE TITLE
Use new macros in templates

### ISSUE THREAD

**Issue by xprazak2** [theforeman/community-templates#339]
PR containing [new macros](https://github.com/theforeman/foreman/pull/3983) was merged into core. We should use new macros:

`host_enc` instead of `@host.info`
`host_param_true?` instead of `@host.param_true?`
`host_param_false?` instead of `@host.param_false?`
`host_param('param_name')` instead of `@host.params['param_name']`

**Comment by ares** [comment]
should be addressed by https://github.com/theforeman/community-templates/pull/343
