### ISSUE TITLE
Support DHCP (v4) during installation, static (v6 only) after installation

### ISSUE THREAD

**Issue by jovandeginste** [theforeman/community-templates#356]
We manage machines via IPv6 only; however not everything supports this, so we start the installation via DHCP IPv4, then configure the network interfaces and after the reboot only use IPv6 for the management interface. Schematically:

* pxe over `eth0`: v4, dhcp
* anaconda+kickstart (still `eth0`): v4 (dhcp address)
* kickstart configures network interfaces, including `eth0`
  * `eth0` will have a (static) v6 address, _no_ v4 address
* after reboot, no v4 address left for `eth0` (other interfaces probably still have a v4 address)

I found no way to model the subnet for `eth0`. Any tips?

**Comment by ares** [comment]
The only idea I have is to clone the snippet and hardcode the configuration. Then update the kickstarg template to use that snippet. Maybe foreman_hooks could be used to change host interface configuration, once the host is built. Or if you're deploying vms, you could add 2 interfaces and remove the provisioning one from the hook.

**Comment by tbrisker** [comment]
On behalf of the Foreman team, thank you for your contribution to the Foreman community templates repository! 
This repository is being archived and all templates are migrated to the relevant repositories. If you wish to pursue this issue, please re-open the issue against the relevant project in our [issue tracker](https://projects.theforeman.org). 
For more information and background, please [click here]( https://community.theforeman.org/t/heads-up-community-templates-repo-will-be-archived-tomorrow/19539).
