### ISSUE TITLE
Add windows specific user data templates

### ISSUE THREAD

**Issue by edestecd** [theforeman/community-templates#358]
I am doing some work on windows specific user data templates for EC2 and VSphere.
Are we open to having these in this repo?

**Comment by ekohl** [comment]
I don't know how they'd look, but as long as they're useful to other Foreman users I'm sure we're open to it.

**Comment by edestecd** [comment]
In VShere fog uses the vmware customization for templates.
Something like this:
https://www.inovex.de/blog/deploying-windows-server-with-foreman-in-vsphere/

For AWS user data is just powershell. So just installing puppet with chocolatey and kicking off a no such tags run, should be a good start

**Comment by ekohl** [comment]
That sounds like it belongs in this repo. Not sure how many people can currently review those patches, but we can always add more members.

**Comment by tbrisker** [comment]
On behalf of the Foreman team, thank you for your contribution to the Foreman community templates repository! 
This repository is being archived and all templates are migrated to the relevant repositories. If you wish to pursue this issue, please re-open the issue against the relevant project in our [issue tracker](https://projects.theforeman.org). 
For more information and background, please [click here]( https://community.theforeman.org/t/heads-up-community-templates-repo-will-be-archived-tomorrow/19539).
