### ISSUE TITLE
enable-puppetlabs-pc1-repo not honored on CentOS 7.3 install

### ISSUE THREAD

**Issue by Yamakasi** [theforeman/community-templates#368]
When I set enable-puppetlabs-pc1-repo: 'true' (which is no boolean but works on Fedora installs) to a CentOS 7.3 install the repo is not added and there is still the Puppet 3.6.x version on CentOS 7.3

Is this a bug or what do I do wrong ?

**Comment by Yamakasi** [comment]
It seems that this is ignored from my finish preview:

rpm -Uvh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm




if [ -f /usr/bin/dnf ]; then
  dnf -y install puppet-agent
else
  yum -t -y install puppet-agent
fi

**Comment by ekohl** [comment]
Is your template exactly like in our repo is it different?

**Comment by Yamakasi** [comment]
It's a copy/paste from your repo.

2017-03-08 8:57 GMT+01:00 Ewoud Kohl van Wijngaarden <
notifications@github.com>:

**Comment by Yamakasi** [comment]
This seems to be solved on he latest template from 1 march. Thanks for updating this ticket ;)
