### ISSUE TITLE
kickstart_default.erb => needs local mirror updates

### ISSUE THREAD

**Issue by Yamakasi** [theforeman/community-templates#381]
This file needs updates so we can simply use the mediapath without the --url url= part for our local repo's.

In this case it also needs updates for Fedora Server as redhat-lsb-core is not in there and we need a fix for group ignore when you add a local updates repo.

**Comment by evgeni** [comment]
Can you elaborate a bit more please?
How exactly should your mediapath line look like? How do you build your local repos, how are they accessible?

Also I think Fedora does have `redhat-lsb-core`: https://apps.fedoraproject.org/packages/redhat-lsb

**Comment by mmoll** [comment]
no reaction, closing.
