### ISSUE TITLE
Ubuntu 17.04 Unable to locate package Puppet in Finish script

### ISSUE THREAD

**Issue by Yamakasi** [theforeman/community-templates#387]
It seems that something goes wrong in the finish template or so. I actually doubt something it wrong but Ubuntu 17.04 fails on "Unable to locate package puppet"

Anyone an idea ? Apt-get update is runned.

**Comment by ekohl** [comment]
Does it show up when you ```apt search puppet```? What's in your sources.list?

**Comment by Yamakasi** [comment]
I found the issue. The puppet package was still default in provision script
as both scripts were not updated simultaneously back the days on github as
far as I can see so I had a difference there. Investigating further if the
deploy goes well. Thanks!

2017-05-02 17:39 GMT+02:00 Ewoud Kohl van Wijngaarden <
notifications@github.com>:

**Comment by mmoll** [comment]
A stock 17.04 install is working just fine with current templates.

**Comment by Yamakasi** [comment]
Yes it seems so, but there was some delay between your changes on the
templates that messed it up... in the time you were cleaning up stuff here.
I had to update another template again.

2017-05-03 13:33 GMT+02:00 Michael Moll <notifications@github.com>:
