### ISSUE TITLE
Add templates for all OSes, maybe?

### ISSUE THREAD

**Issue by bittner** [theforeman/community-templates#413]
The Foreman is nice, but setting up machines for the first time is a bit of a hack in the user interface.

The "Create Operating System" dialog in `Hosts > Operating systems ` can't be filled in in a single pass. You have to:

1. first create a OS (fill in first 3 tabs), and save it
1. then go to the `Hosts > Provisioning templates` and associate them (minimum 3, e.g. the "default", "default finish" and "default PXELinux") with the newly created OS
1. then go back to your OS in `Hosts > Operating systems `, and fill in tab 4 (the templates) -- *which feels dumb in our case since there is only a single choice for each combo box, by the way*
1. then go to ` Hosts > Architectures`, and add the OS to your target architectures.

The situation would be a lot better if there were "Operating systems" already set up in the Hosts menu. The typical values for all supported OSes would do it. You could then adapt or delete them at your liking.

Is there a reason why this has not been done up to the present?

(Is this something that has to happen in another project or repository, not this one?)

**Comment by mmoll** [comment]
This is a long standing usability problem, unrelated to this repository.

**Comment by ekohl** [comment]
I do know that today there will be a meeting to investigate what can be done to the usability, but like @mmoll said: that's not really the goal of this repository.

**Comment by bittner** [comment]
Thanks for the feedback!

I assume, when you say "usability problem", you both refer to the Foreman user interface workflow. While this is an issue, I'm not so much worried about that. Because, as soon as the OSes are set up there's little to worry about.

I'm really saying, doesn't it make sense to pre-populate the "Operating systems" in The Foreman with all supported, commonly used OSes by default? And, optionally, maybe give an option to install only a subset of this pre-populated data (which would include both the templates currently in this repo and the OSes) to reduce clutter already at time of installation?

I'm not ranting, I'm really asking for the right place to make a PR in order to make this happen. (And, of course, trying to find out if there is agreement.)

**Comment by GregSutcliffe** [comment]
I'm not sold on the idea of adding every OS to Foreman by default, my gut feeling is that it would take quite some maintenance / testing. Making it *easy* to add new OSs seems the right approach.

However, your suggestion is a potential workaround. If you do want to try and make it work for a fresh install, though, the right place would be the database seeds - https://github.com/theforeman/foreman/tree/develop/db/seeds.d - you'd probably want to add a new file fairly late on (say 13+ after the proxy features are seeded).
