### ISSUE TITLE
Puppet service not started on Ubuntu

### ISSUE THREAD

**Issue by bittner** [theforeman/community-templates#414]
When provisioning an Ubuntu box (e.g. 17.04 Zesty) then the `puppet` service is not being started (enabled). This may be due to some code in [provisioning_templates/snippet/puppet_setup.erb](https://github.com/theforeman/community-templates/blob/develop/provisioning_templates/snippet/puppet_setup.erb#L112-L145), which probably unsuccessfully tries to make this work for Ubuntu.

Specifically, `facter` never yields a value for neither `os_name` nor `os_major`, which are [used in the `if`](https://github.com/theforeman/community-templates/blob/develop/provisioning_templates/snippet/puppet_setup.erb#L113-L119) that tries to work around Puppet issues [PA-136](https://tickets.puppetlabs.com/browse/PA-136) and [PUP-5577](https://tickets.puppetlabs.com/browse/PUP-5577) (as quoted in the comment). Not sure if this observation points into the right direction.

On a fresh Ubuntu Zesty node the output of `facter` only contains two properties starting with`os`:
```ruby
$ facter | grep ^os
os => {"name"=>"Ubuntu", "family"=>"Debian", "release"=>{"major"=>"17.04", "full"=>"17.04"}, "lsb"=>{"distcodename"=>"zesty", "distid"=>"Ubuntu", "distdescription"=>"Ubuntu 17.04", "distrelease"=>"17.04", "majdistrelease"=>"17.04"}}
osfamily => Debian
```
(Note: The node under test was rebooted twice after provisioning; once after the OS installation, as foreseen, and the second time after manually running `service puppet start` and a subsequent installation of software by the Puppet agent.) 

Software being used/installed on a fresh node is:
```bash
$ puppet --version
4.8.2
$ facter --version
2.4.6
```
Is this problem already known?

**Comment by ekohl** [comment]
```os_name``` and ```os_major``` are provided by Foreman so I'm interested in how your Operating System in Foreman is configured.

**Comment by bittner** [comment]
The setup of the operating system in Foreman looks like this:

(Operating System tab)
- **Name:** Ubuntu
- **Major version:** 17
- **Minor verison:** 04
- **Description:** Ubuntu 17.04 Zesty Zapus
- **Family:** Debian
- **Release name:** zesty

(Partition table tab)
- **Selected items:** Preseed default

(Installation media tab)
- **Selected items:** Ubuntu mirror

(Templates tab)
- **Provisioning template:** Preseed default
- **Finish template:** Preseed default finish
- **PXELinux template:** Preseed default PXELinux

I would have guessed that the "Finish template" was responsible for installing things like the Puppet agent (service), but looking at the template source in the Foreman UI it looks more like the "Provisioning template" deals with OS related decisions.

The top of the file looks like this:

``` erb
<%#
kind: provision
name: Preseed default
oses:
- Debian
- Ubuntu
%>
<%
  proxy_string = @host.params['http-proxy'] ? " http://#{@host.params['http-proxy']}:#{@host.params['http-proxy-port']}" : ''
  salt_enabled = @host.params['salt_master'] ? true : false
  os_major = @host.operatingsystem.major.to_i
  squeeze_or_older = (@host.operatingsystem.name == 'Debian' && os_major <= 6)
%>
# Locale
```
The bottom of the very same file:
``` erb
# Boot loader settings
#grub-pc grub-pc/hidden_timeout boolean false
#grub-pc grub-pc/timeout string 10
d-i grub-installer/only_debian boolean true
d-i grub-installer/with_other_os boolean true
<% if @host.params['install-disk'] -%>
d-i grub-installer/bootdev string <%= @host.params['install-disk'] %>
<% elsif (@host.operatingsystem.name == 'Debian' and @host.operatingsystem.major.to_i >= 8) or (@host.operatingsystem.name == 'Ubuntu' and @host.operatingsystem.major.to_i >= 16) -%>
d-i grub-installer/bootdev string default
<% end -%>
d-i finish-install/reboot_in_progress note

d-i preseed/late_command string wget -Y off <%= @static ? "'#{foreman_url('finish')}&static=true'" : foreman_url('finish') %> -O /target/tmp/finish.sh && in-target chmod +x /tmp/finish.sh && in-target /tmp/finish.sh
```
For both templates the Foreman UI complains when I click the "Preview" button:

(Preseed default)
> Warning! There was an error rendering the Preseed default template: undefined method `layout' for nil:NilClass

(Preseed default finish)
> Warning! There was an error rendering the Preseed default finish template: ERF42-7327 [Foreman::Exception]: The snippet 'preseed_networking_setup' threw an error: undefined method `dhcp_boot_mode?' for nil:NilClass

Anything else you need for an analysis?

**Comment by ekohl** [comment]
Which Foreman version are you using? I get the feeling that you're using templates that rely on features only present in recent Foreman versions.

In case you're syncing using the templates plugin we do have x.y-stable branches for when you're unable to update your Foreman.

**Comment by bittner** [comment]
The Foreman About page says: Version 1.15.3

**Comment by ekohl** [comment]
It sounds like the host to provision has no subnet or partition table assigned. Can you check that?

**Comment by bittner** [comment]
In The Foreman we have a subnet defined (Name foobar-internal, Address 172.23.53.0/24, Domains foobar.local, VLAN-ID _none_, DHCP-Proxy _none_), which seems to be attached to the host implicitly via the "Host Group". The partition table is of course assigned ("Preseed default").

The Host Group in The Foreman, interestingly, has the values set to Debian, but I assume these are only defaults to fill in in the form when a new host is created via the UI. In the host itself we clearly have these values set to the corresponding Ubuntu ones.

Can you maybe explain where the values come from that get interpreted in the templates? (What is `@host.operatingsystem.name`, for example? If `@host` contained all values spit out by `facter` that wouldn't make sense, because the `operatingsystem` value is really a string on both Ubuntu and Debian installations, not a dictionary with keys `name`, `major`, etc.)

**Comment by ekohl** [comment]
> The Host Group in The Foreman, interestingly, has the values set to Debian, but I assume these are only defaults to fill in in the form when a new host is created via the UI. In the host itself we clearly have these values set to the corresponding Ubuntu ones.

The Host Group is "only" a set of defaults when creating a host, any host can have a different value.

> Can you maybe explain where the values come from that get interpreted in the templates? (What is @host.operatingsystem.name, for example? If @host contained all values spit out by facter that wouldn't make sense, because the operatingsystem value is really a string on both Ubuntu and Debian installations, not a dictionary with keys name, major, etc.)

```@host``` is the ```Host``` model in Foreman. Facter only comes into play later because Puppet reports include facts and some values are overridden. During provisioning Foreman relies solely on its own data and you can ignore facter. ```@host.operatingsystem``` refers to the ```Operatingsystem``` model that's assigned to the host. That value has properties like ```name``` and ```major```. (There is a desire to decouple these values more from the database model but AFAIK no concrete plan yet.)

The error implies that the host has no subnet so I'd look at the interfaces tab of the host edit page and see if it's properly configured. Not sure where the layout error comes from but generally you approach it the same way: look at the template, see which data it's trying to read and look at the relevant data within Foreman.
