### ISSUE TITLE
CoreOS templates need to be rewritten to use Ignition instead of cloud-config

### ISSUE THREAD

**Issue by mimmus** [theforeman/community-templates#424]
cloud-config is now deprecated, Ignition is the official configuration tool.

**Comment by mmoll** [comment]
somebody should pick up GH-389

**Comment by tbrisker** [comment]
On behalf of the Foreman team, thank you for your contribution to the Foreman community templates repository! 
This repository is being archived and all templates are migrated to the relevant repositories. If you wish to pursue this issue, please re-open the issue against the relevant project in our [issue tracker](https://projects.theforeman.org). 
For more information and background, please [click here]( https://community.theforeman.org/t/heads-up-community-templates-repo-will-be-archived-tomorrow/19539).
