### ISSUE TITLE
Autoyast Template behind Proxy

### ISSUE THREAD

**Issue by thiema** [theforeman/community-templates#429]
Running template (provisioning template for SLES/Suse: e.g. provisioning_templates/provision/autoyast_sles_default.erb) without direct route to internet wont work.

I usually configure the base installation media using a local file server, but when it is about puppet installation e.g. the following part from template :
`<add-on>
    <add_on_products config:type="list">
<% if puppet_enabled -%>
<% if host_param_true?('enable-puppetlabs-pc1-repo') -%>
    <listentry>
        <media_url><![CDATA[http://yum.puppetlabs.com/sles/<%= os_major %>/PC1/<%= @host.architecture %>/]]></media_url>
<name>puppet</name>
...
`
I would like to use the remote repository. I havent managed to access it, even when setting up a proxy
using xml `<proxy>...</proxy>.`

Is there a recommended way to run the provisioning template behind a proxy ?

**Comment by ekohl** [comment]
Currently I don't think there is a recommended way. I haven't used Suse but maybe @timogoebel or @mmoll know. Patches are always welcome.

**Comment by mmoll** [comment]
see GH-388

**Comment by hboetes** [comment]
As someone who uses suse installs with a proxy I can concur that without me changing anything all of the sudden my autoyast installs are getting stuck at the very point mentioned by @thiema.

Silly thing is that the proxy shows it got the requested files without problem. Also interesting is that the add-on product seems to be attempted to be installed with the pre-scripts.

At that moment no files are installed and no logfiles are generated and the message are visible in the fancy interface which makes the error pop up and hide within a second. This makes debugging the problem really hard.

It's a bit of a mystery  to me, why this fails.

**Comment by hboetes** [comment]
I also noted that if I disable the proxy, I got the same error.

**Comment by hboetes** [comment]
Now that you mention it...

https://github.com/theforeman/community-templates/pull/437/commits/a84485e930180c39c191bebbce6c1bdba847a22f

Or get pull request: https://github.com/theforeman/community-templates/pull/437

@thiema, please get this pull request and give it a spin and see if it fixes your issue.

**Comment by mmoll** [comment]
I presume this is fixed with GH-437.
