### ISSUE TITLE
network config in CoreOS cloudconfig snippet is too generic

### ISSUE THREAD

**Issue by mimmus** [theforeman/community-templates#433]
Unit:

```
- name: down-interfaces.service
            command: start
            content: |
              [Service]
              Type=oneshot
              ExecStart=/usr/bin/bash -c 'for i in $(/usr/bin/ls /sys/class/net/); do [ $i == "lo" ] || (/usr/bin/ip link set $i down; /usr/bin/ip addr flush dev $i); done'
          - name: systemd-networkd.service
command: restart
```

(used to reset interfaces when static IP is used) is too generic, only 'lo' is excluded and it sets down/flushes also Docker interfaces (docker0, vethXXX., ...).

Another 'logic' is needed. I used a 'positive logic' and reset only  ens* interfaces, but this is valid only for VMware VMs.

**Comment by ekohl** [comment]
Could you come up with a PR that implements your changes?

**Comment by mimmus** [comment]
I have not the "definitive" solution for every environment.
On VMware, I solved using ens* as filter but on bare-metal it will be different:
`ExecStart=/usr/bin/bash -c 'for i in $(/usr/bin/ls /sys/class/net/); do if [[ $i == ens* ]]; then (/usr/bin/ip link set $i down; /usr/bin/ip addr flush dev $i); fi; done'`

**Comment by tbrisker** [comment]
On behalf of the Foreman team, thank you for your contribution to the Foreman community templates repository! 
This repository is being archived and all templates are migrated to the relevant repositories. If you wish to pursue this issue, please re-open the issue against the relevant project in our [issue tracker](https://projects.theforeman.org). 
For more information and background, please [click here]( https://community.theforeman.org/t/heads-up-community-templates-repo-will-be-archived-tomorrow/19539).
