### ISSUE TITLE
Add support for non-free and contrib repositories to Debian

### ISSUE THREAD

**Issue by tullis** [theforeman/community-templates#453]
The preseed configuration for Debian has the ability to configure the 'contrib' and 'non-free' components with the following keys:

```
# You can choose to install non-free and contrib software.
#d-i apt-setup/non-free boolean true
#d-i apt-setup/contrib boolean true
```

https://www.debian.org/releases/stretch/amd64/apbs04.html.en

It would be useful to be able to control these during a deployment with Foreman, using the community preseed template.

Thanks.

**Comment by mmoll** [comment]
@tullis could you open a PR with these changes? best with a paramter per repo...

**Comment by tullis** [comment]
Will do.

**Comment by tbrisker** [comment]
On behalf of the Foreman team, thank you for your contribution to the Foreman community templates repository! 
This repository is being archived and all templates are migrated to the relevant repositories. If you wish to pursue this issue, please re-open the issue against the relevant project in our [issue tracker](https://projects.theforeman.org). 
For more information and background, please [click here]( https://community.theforeman.org/t/heads-up-community-templates-repo-will-be-archived-tomorrow/19539).
