### ISSUE TITLE
Make use of param_true? and snippet_if_exist

### ISSUE THREAD

**Issue by lzap** [theforeman/community-templates#52]
Once Foreman 1.5 is out and users had time to upgrade, we can make use of these two new functions that has been added in https://github.com/theforeman/foreman/pull/1178 (Foreman 1.4 release).

Templates will be cleaner a bit and will allow users to "redefine" snippets with their own separate templates.

**Comment by mmoll** [comment]
is that still relevant?

could ```@host.params['force-puppet'] && @host.params['force-puppet'] == 'true'``` replaced by ```param_true? force-puppet```

**Comment by lzap** [comment]
Yup, that's what we can do now.

**Comment by mmoll** [comment]
I'll take that, as soon as I find time :)

**Comment by ekohl** [comment]
Let me know when you find the source because I'm in need of some time as well :)
