### ISSUE TITLE
Remove () from filename

### ISSUE THREAD

**Issue by Pimmetje** [theforeman/community-templates#553]
May i suggest removing the () from the filename https://github.com/theforeman/community-templates/blob/develop/provisioning_templates/provision/freebsd_(mfsbsd)_provision.erb

This causes issues for the for some template handling like https://github.com/theforeman/foreman_templates (here the template get escaped)

The issue could also be fixed on the other side. But i think it's better to not use () in filenames anyway.

**Comment by lzap** [comment]
@ares and @mmoll ? That was terrible idea from the day one for sure. Renaming needs migration, does it? So patch into templates and then migration in core for 1.22.

**Comment by mmoll** [comment]
I'm not against it :+1:

**Comment by tbrisker** [comment]
On behalf of the Foreman team, thank you for your contribution to the Foreman community templates repository! 
This repository is being archived and all templates are migrated to the relevant repositories. If you wish to pursue this issue, please re-open the issue against the relevant project in our [issue tracker](https://projects.theforeman.org). 
For more information and background, please [click here]( https://community.theforeman.org/t/heads-up-community-templates-repo-will-be-archived-tomorrow/19539).
