### ISSUE TITLE
puppet_run_once_-_ssh_default.erb not working on Debian and Ubuntu

### ISSUE THREAD

**Issue by brimioulle** [theforeman/community-templates#564]
When running puppet_run_once_-_ssh_default.erb puppet path is not resolved for Debian and Ubuntu hosts. Suggested fix:
Replace line
puppet agent --onetime --no-usecacheonfailure --no-daemonize <%= input("puppet_options") %>
by
export PATH=$PATH:/opt/puppetlabs/bin/; puppet agent --onetime --no-usecacheonfailure --no-daemonize <%= input("puppet_options") %>

Same error when running ansible role for puppet. Suggested fix:
Add environment:
      environment:
        PATH: '/opt/puppetlabs/bin:{{ ansible_env.PATH }}'

**Comment by tbrisker** [comment]
On behalf of the Foreman team, thank you for your contribution to the Foreman community templates repository! 
This repository is being archived and all templates are migrated to the relevant repositories. If you wish to pursue this issue, please re-open the issue against the relevant project in our [issue tracker](https://projects.theforeman.org). 
For more information and background, please [click here]( https://community.theforeman.org/t/heads-up-community-templates-repo-will-be-archived-tomorrow/19539).
