### ISSUE TITLE
Make template default

### ISSUE THREAD

**Issue by Garreat** [theforeman/community-templates#576]
Is there a way to make template 'Default' field checked?
Probably some metadata field?
I tried 'default: true', without success.

**Comment by ares** [comment]
I guess we lack the support for this then. Mind to open RFE or even a PR? Should be easy to add to similar line like https://github.com/theforeman/foreman/blob/develop/app/models/template.rb#L94

**Comment by tbrisker** [comment]
On behalf of the Foreman team, thank you for your contribution to the Foreman community templates repository! 
This repository is being archived and all templates are migrated to the relevant repositories. If you wish to pursue this issue, please re-open the issue against the relevant project in our [issue tracker](https://projects.theforeman.org). 
For more information and background, please [click here]( https://community.theforeman.org/t/heads-up-community-templates-repo-will-be-archived-tomorrow/19539).
