### ISSUE TITLE
Ansible Power action doesn't trigger a reboot

### ISSUE THREAD

**Issue by snagoor** [theforeman/community-templates#591]
Running the Ansible Power job doesn't trigger a reboot on the target host. 

Here are the logs captured from the target client  from `/var/log/messages`

~~~
Jun 26 01:20:43 rhel8 ansible-command[1596]: Invoked with _raw_params=echo restart host && sleep 3#012 shutdown -r +1 warn=True _uses_shell=False argv=None chdir=None executable=None creates=None removes=None stdin=None
~~~

When ansible doesn't have a Shell, reboot silently fails.

**Comment by ares** [comment]
Resolved
