### ISSUE TITLE
iPXE global default menus items do not match content

### ISSUE THREAD

**Issue by canihavethisone** [theforeman/community-templates#602]
menu has:
item --key d discovery Discovery from ${next-server}:8000 (httpboot module)
item --key d discovery8448 Discovery from ${next-server}:8448 (httpboot module)
item --key d discovery80 Discovery from ${next-server}:80 (custom script)

however content is:
:discovery 
:discovery80
:discovery8000

Also, :discovery and :discovery8000 are identical except for the inclusion of /httpboot in path.  Any time I do an install or upgrade I append this to :discovery (as its the most logical entry to change settings => Default PXE global template entry to). 

I think that either the menu items need fixing, or discovery changed to include httpboot in path, or both.

:discovery
dhcp
kernel http://${next-server}:8000/httpboot/boot/fdi-image/vmlinuz0 initrd=initrd0.img rootflags=loop root=live:/fdi.iso rootfstype=auto ro rd.live.image acpi=force rd.luks=0 rd.md=0 rd.dm=0 rd.lvm=0 rd.bootif=0 rd.neednet=0 nomodeset nokaslr proxy.url=<%= foreman_server_url %> proxy.type=foreman BOOTIF=01-${net0/mac}
initrd http://${next-server}:8000/httpboot/boot/fdi-image/initrd0.img
imgstat
sleep 2
boot || goto failed
goto start

**Comment by lzap** [comment]
https://github.com/theforeman/community-templates/pull/616
