### ISSUE TITLE
Report of applicable packages

### ISSUE THREAD

**Issue by roboneci** [theforeman/community-templates#612]
Hello,
i want to create Report template where all applicable packages can be shown. I want to change applicable_errata.erb but i'm not programmer and i can't find what includes is known to foreman. Could someone give me some link where all includes are described so i can create such report?

Thanks a lot for any hint.

**Comment by ares** [comment]
Hello, we're working on improving the docs about writing report templates. The best material we have for writing templates in general is this https://projects.theforeman.org/projects/foreman/wiki/TemplateWriting#Templates but it talks about provisioning templates. Report templates uses some other macros. You can copy the same structure from applicable_errata but you'll need to find the right methods on content_facet of a host, that gives you the list. The best thing you can do is hop on our theforeman-dev irc channel and ask for help there. Katello devs should be able to help.

**Comment by tbrisker** [comment]
On behalf of the Foreman team, thank you for your contribution to the Foreman community templates repository! 
This repository is being archived and all templates are migrated to the relevant repositories. If you wish to pursue this issue, please re-open the issue against the relevant project in our [issue tracker](https://projects.theforeman.org). 
For more information and background, please [click here]( https://community.theforeman.org/t/heads-up-community-templates-repo-will-be-archived-tomorrow/19539).
