### ISSUE TITLE
AutoYaST SLES 15

### ISSUE THREAD

**Issue by dirktimmer** [theforeman/community-templates#654]
Hi,
because SuSE don't provide anymore full installation media since SLES 15, you must register  during provisioning.
Therefor I have created a complete new template. Perhaps you can merge it with the Default template. With my template, you must add parameter owner_email in the Operating System, additional you must add host parameter reg_key for each host.
I have removed the the opensuse puppet repository, because it doesn't exist anymore. If you set enable-puppetlabs-puppet6-repo, it will install Puppet 6, otherwise it will install Puppet 5 from yum.puppet.com.
Best regards,
Dirk
[autoyast_sles_15.erb.txt](https://github.com/theforeman/community-templates/files/3790516/autoyast_sles_15.erb.txt)

**Comment by tbrisker** [comment]
On behalf of the Foreman team, thank you for your contribution to the Foreman community templates repository! 
This repository is being archived and all templates are migrated to the relevant repositories. If you wish to pursue this issue, please re-open the issue against the relevant project in our [issue tracker](https://projects.theforeman.org). 
For more information and background, please [click here]( https://community.theforeman.org/t/heads-up-community-templates-repo-will-be-archived-tomorrow/19539).
