### ISSUE TITLE
[RFC] Anyone thought about implementing `nmcli` in the templates?

### ISSUE THREAD

**Issue by jovandeginste** [theforeman/community-templates#657]
Recently I was working on a side project, configuring Fedora 31 laptops. As usual we copied over `ifcfg` files, and then restarted the NetworkManager so it picks up the new configuration.

I then had to configure 802.1x and VPN profiles, and I started to realize this could be done easier with `nmcli`. Now I'm configuring all the interfaces using `nmcli`, which means acually less configuration.

I was wondering if anyone already looked into this for the server side of things... And if there was anything against this.

**Comment by ares** [comment]
IIRC there were some issues with bonds on rhel6, which was why we picked a different way of configuration. I'm all for modernizing the way how we configure networking. Perhaps the better place to start the RFC is https://community.theforeman.org/c/development where you get larger audience.

**Comment by lzap** [comment]
There is one major problem - nmcli talks to NetworkManager via DBUS. Our snippets are executed in the Anaconda post stage when the system hasn't been booted yet. All we can achieve at that point is chroot but that's not enough.

As much as I'd love to see something like https://docs.ansible.com/ansible/latest/modules/nmcli_module.html to be involved that's the very same problem. I suggest to stick with ifcfg files, even RHEL8 defaults to them.

**Comment by jovandeginste** [comment]
I see, this should close this issue as unactionable (for now)
