### ISSUE TITLE
Outdated Yum Repo URL for Puppet 6

### ISSUE THREAD

**Issue by learnitall** [theforeman/community-templates#658]
Hey all,

I've been trying to use [puppetlabs_repo.erp](https://github.com/theforeman/community-templates/blob/develop/provisioning_templates/snippet/puppetlabs_repo.erb) to install the Puppet 6 repository during provisioning on a CentOS7 system. I'm using PXELinux with provisioning templates [Kickstart default](https://github.com/theforeman/community-templates/blob/develop/provisioning_templates/provision/kickstart_default.erb) and [Kickstart default finish](https://github.com/theforeman/community-templates/blob/develop/provisioning_templates/finish/kickstart_default_finish.erb). I've set the `enable-puppetlabs-puppet6-repo` parameter to `true` with type `boolean` to enable the snippet in the kickstart templates. However, unattended installation of Puppet 6 Agent fails with this setup.

I believe the root cause of this issue is that when I view the rendered finishing template through the web GUI, the Puppet 6 repository URL is set to https://yum.puppet.com/puppet6/puppetlabs-release-puppet6-el-7.noarch.rpm, however the following command:

```
rpm -Uvh https://yum.puppet.com/puppet6/puppetlabs-release-puppet6-el-7.noarch.rpm
```

fails with a 404 error. The current [Puppet 6 documentation](https://puppet.com/docs/puppet/6.0/puppet_platform.html#task-383) states that the repository URL is now actually https://yum.puppet.com/puppet6-release-el-7.noarch.rpm. I believe the puppetlabs_repo snippet should be updated accordingly, however since I don't have much experience writing templates and am a bit short on time at the moment to figure it out, I thought I'd raise the issue here before submitting a pull request.

Thanks!

**Comment by ekohl** [comment]
I believe this was fixed in 1ad37688ef1790b1f6fdd186e1738678cadcd4d6
