### ISSUE TITLE
Add username & password to user-data template

### ISSUE THREAD

**Issue by nodermatt** [theforeman/community-templates#663]
Thanks for the templates, I'm working on adding the templates to the deployment process.

Can someone help me how to define the username and password in the user-data template? I am using the [opn-vm-tools](https://github.com/theforeman/foreman_userdata/blob/master/app/views/foreman/unattended/provisioning_templates/user_data/userdata_open_vm_tools.erb) template

As described by the step "The template needs to have a username and password set up for Foreman to SSH in after provisioning and run the finish script." in the [documentation](https://www.theforeman.org/manuals/1.23/#5.2.9VMwareNotes)

**Comment by lzap** [comment]
Hey, please use our discourse forum for these.

SSH finish template works in a way that Foreman connects to the host via SSH, it either needs SSH key or username/password associated with the image. You go to Compute Resource - Images and set username and password there.
