### ISSUE TITLE
kickstart default ipxe using wrong variable name for ksdevice parameter

### ISSUE THREAD

**Issue by jpasqualetto** [theforeman/community-templates#664]
Variable @host.mac is being used to generate the kernel line in kickstart default ipxe. When a host has a provision interface which is not the primary interface this will be the wrong mac address to be used.

Right variable is defined as mac in the beginning of the template:

~~~
  ...
  major = @host.operatingsystem.major.to_i
  iface = @host.provision_interface
  mac = @host.provision_interface.mac
  hostname = @host.name
 ...
~~~
However, in the kernel line wrong variable is still used:

~~~
... ksdevice=<%= @host.mac %> network kssendmac ...
~~~

**Comment by lzap** [comment]
I guess this was fixed in https://github.com/theforeman/community-templates/pull/665 so closing. Thank you!
