### ISSUE TITLE
ipxe_global_default.erb first entry missing httpboot in path

### ISSUE THREAD

**Issue by canihavethisone** [theforeman/community-templates#676]
according to my testing, lines 49 and 50 should be:

    kernel http://${next-server}:8000/httpboot/boot/fdi-image/vmlinuz0 initrd=initrd0.img rootflags=loop root=live:/fdi.iso rootfstype=auto ro rd.live.image acpi=force rd.luks=0 rd.md=0 rd.dm=0 rd.lvm=0 rd.bootif=0 rd.neednet=0 nomodeset nokaslr proxy.url=<%= foreman_server_url %> proxy.type=foreman BOOTIF=01-${net0/mac}

    initrd http://${next-server}:8000/httpboot/boot/fdi-image/initrd0.img

instead of :

    kernel http://${next-server}:8000/boot/fdi-image/vmlinuz0 initrd=initrd0.img rootflags=loop root=live:/fdi.iso rootfstype=auto ro rd.live.image acpi=force rd.luks=0 rd.md=0 rd.dm=0 rd.lvm=0 rd.bootif=0 rd.neednet=0 nomodeset nokaslr proxy.url=<%= foreman_server_url %> proxy.type=foreman BOOTIF=01-${net0/mac}

    initrd http://${next-server}:8000/boot/fdi-image/initrd0.img

**Comment by ekohl** [comment]
Could you send a pull request for this? It's easier to review and if merged, you actually get the credit in the changelog.

**Comment by lzap** [comment]
Thanks for the report: https://github.com/theforeman/community-templates/pull/695
